### PR TITLE
pos_mobile: fix styles

### PR DESCRIPTION
**Pull request by GabbasovDinar**

### CODE REVIEW

**Comment by yelizariev** [comment]
:rainbow: has to be used when *works in the same way, but **code** is better organized, refactored, commented or cleaned up*, which is not the case. Please fix

**Comment by yelizariev** [comment]
Also, please explain in commit message or probably in a code why those updates speed up clicking

**Comment by GabbasovDinar** [comment]
@yelizariev Each time a function is called, the click event is recorded without removing the previous event. When you click the menu button, the event was generated many times, which led to a hang

**Comment by yelizariev** [comment]
@GabbasovDinar Can we just subscribe handler only once?

**Comment by GabbasovDinar** [comment]
@yelizariev the error was caused by incorrect selector definition

**Review by yelizariev — DISMISSED** [review]

**Review by yelizariev — APPROVED** [review]

**Pull request merged**
