### PR TITLE
12.0 cancel

### PR DESCRIPTION
**Pull request by GabbasovDinar**

### CODE REVIEW

**Comment by yelizariev** [comment]
Depends on https://github.com/it-projects-llc/pos-addons/pull/795

**Review by Ramil-Mukhametzyanov — APPROVED** [review]
smoothly approved

**Review by Ramil-Mukhametzyanov — CHANGES_REQUESTED** [review]
I forgot to point out the bad design: part of the input in the request reason form is beyond the border of the form.

**Comment by GabbasovDinar** [comment]
> I forgot to point out the bad design: part of the input in the request reason form is beyond the border of the form.

@Ramil-Mukhametzyanov where screenshot?

**Comment by Ramil-Mukhametzyanov** [comment]
> @Ramil-Mukhametzyanov where screenshot?
[Here](https://drive.google.com/file/d/1dOQDvMBmY_XWp7NJT8wehyVchuwIqMm8/view)

**Comment by GabbasovDinar** [comment]
@Ramil-Mukhametzyanov I don't have the problem. 
screenshot-pos odoo12 local-2018 11 13-15-05-27

**Review by Ramil-Mukhametzyanov — APPROVED** [review]

**Review by yelizariev — APPROVED** [review]

**Pull request merged**
