### PR TITLE
11.0 1696b38119ac6a9fd408605df86f71a9e2a16a96

### PR DESCRIPTION
**Pull request by GabbasovDinar**

### CODE REVIEW

**Review by Ramil-Mukhametzyanov — CHANGES_REQUESTED** [review]
There is no History button in POS

**Review by Ramil-Mukhametzyanov — CHANGES_REQUESTED** [review]
1. Enable pre-receipt
2. Apply custom receipt
3. In POS, Click on 'Bill'
Result : Odoo server error on browser and 'mismatched tag' error in POSBox.
Odoo server error is repeated periodically.

**Review by Ramil-Mukhametzyanov — CHANGES_REQUESTED** [review]
POS does not apply custom templates when printing receipts and reprinting them from history

**Review by Ramil-Mukhametzyanov — CHANGES_REQUESTED** [review]
Fetch Orders > Click 'Create Order'
Result: "'int' object is not iterable"

**Review by Ramil-Mukhametzyanov — COMMENTED** [review]
> POS does not apply custom templates when printing receipts and reprinting them from history

I have tested it with USB Printer

**Comment by GabbasovDinar** [comment]
> POS does not apply custom templates when printing receipts and reprinting them from history


I cannot reproduce the problem 
image

**Review by Ramil-Mukhametzyanov — APPROVED** [review]
I saw pos_order_receipt_custom worked, but I was having some trouble using a USB Printer.
Skip it now.

**Comment by yelizariev** [comment]
No merge commit here

**Review by Ramil-Mukhametzyanov — COMMENTED** [review]
pos_invoice_pay manifest and changelog are omitted

**Pull request merged**
