### PR TITLE
9.0 Add currency in pos session report

### PR DESCRIPTION
**Pull request by cvinh**
Add currency in pos session report

### CODE REVIEW

**Comment by yelizariev** [comment]
@invitu 
thank you for contribution.
I can accept you pull request only without gitignore file (use can use global gitignore confguration) and without changing indent, because it bloats git blame

**Comment by cvinh** [comment]
Dear @yelizariev ,
.gitignore file is used in every Odoo and OCA repository... why don't you do like them ?
I don't get your indent problem... I think I use "best practice" indentation as Odoo and OCA
Best regards

**Comment by yelizariev** [comment]
@invitu the question is not about way of indentation. It's about bloating git blame https://github.com/odoo/odoo/pull/4531#issuecomment-69105136

As for gitignore I believe there is no gitignore file that suit for every developer (every IDE, file manager etc). So why don't configure global gitignore once in your machine and don't add it to every project

**Comment by cvinh** [comment]
ok, I let you do these improvements

**Comment by yelizariev** [comment]
Thank you

**Pull request merged**
