### PR TITLE
[FIX] fix pos_session_custom2 not working in v9

### PR DESCRIPTION
**Pull request by cvinh**
I tested pos_session_custom2 and it did not work in actual v9
Here is the fix

### CODE REVIEW

**Comment by cvinh** [comment]
small question here : how do you print backend pdf receipt to posbox printer ?

**Comment by yelizariev** [comment]
As for now, It's not possible to print backend pdf to posbox

**Comment by cvinh** [comment]
Would it be good for you to move the session report in frontend ?
Then we could print it on the posbox...

**Comment by yelizariev** [comment]
I don't have such plans

**Comment by cvinh** [comment]
Dear Yvan, here's a tip for you : you can print pdf on a posbox printer by installing a cups raw queue in the posbox (it's readonly, you have to hack it)... Then you can print the pdf session report from any computer in the local network (install the printer driver on every computer)
We did it successfully

**Comment by yelizariev** [comment]
Do you mean, that you are able to print pdf file on ticket printer?
images

**Comment by cvinh** [comment]
yes, a ticket printer (epson tm-t20ii in my case) plugged on a posbox (with cups running on it)

**Pull request merged**
