### PR TITLE
[ADD] Manual Credit Updates

### LINKED ISSUE #297: Notebook Debt Initial Debt [$300 awarded]
# Question : Initial debt
Is there any method to load previos customer debts at install time?.
Workaround:  
Define a product to register previos debt and create the initial debt, all do a bit painfully if there are more than 400 customer with debts.

👍 

<bountysource-plugin>

---
The **[$300 bounty](https://www.bountysource.com/issues/44748670-notebook-debt-initial-debt?utm_campaign=plugin&utm_content=tracker%2F2289114&utm_medium=issues&utm_source=github)** on this issue has been claimed at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F2289114&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by yelizariev**
closes #297

### CODE REVIEW

**Comment by yelizariev** [comment]
@gustavovalverde you are welcome to review. You  can use Runbot -> Details link to open build

**Comment by yelizariev** [comment]
@jclopezar you probably have some opinion about it too

**Comment by gustavovalverde** [comment]
Great @yelizariev! I'll be testing in a few hours.

**Review by ilmir-k — APPROVED** [review]
:+1:

**Pull request merged**
