### PR TITLE
11.0 merge 379d32b

### PR DESCRIPTION
**Pull request by iledarn**

### CODE REVIEW

**Comment by yelizariev** [comment]
pos_longpolling doesn't work. It looks like some updates are lost after merging


2018-03-02 09:47:56,003 5067 INFO openerp_test odoo.modules.loading: loading pos_longpolling/views/pos_longpolling_template.xml
2018-03-02 09:47:56,338 5067 INFO openerp_test odoo.modules.loading: loading pos_longpolling/views/pos_longpolling_view.xml
2018-03-02 09:47:56,521 5067 INFO openerp_test odoo.addons.base.ir.ir_ui_view: Field `query_timeout` does not exist

**Comment by GabbasovDinar** [comment]
@yelizariev I will check

**Comment by GabbasovDinar** [comment]
@yelizariev Can you check PR?

**Review by GabbasovDinar — APPROVED** [review]

**Review by yelizariev — APPROVED** [review]
Quite a few updates. I've only checked that non-ported modules are not merged as installable.

Also, I took a look for PORT commits.

Someone has to check functional part of the modules

**Review by Railia — APPROVED** [review]

**Pull request merged**
