### PR TITLE
:ambulance: not synchronized rescued sessions

### PR DESCRIPTION
**Pull request by KolushovAlexandr**
Also, it can be considered as optimization - decreased amount of DB queries

### CODE REVIEW

**Review by ilmir-k — APPROVED** [review]

**Comment by ilmir-k** [comment]
@yelizariev

**Review by yelizariev — APPROVED** [review]
it makes sense

**Comment by yelizariev** [comment]
@KolushovAlexandr настрой подписи комитов

**Comment by yelizariev** [comment]
I approve to merge it now

**Pull request merged**
