### PR TITLE
12.0 discount

### PR DESCRIPTION
**Pull request by GabbasovDinar**

### CODE REVIEW

**Comment by yelizariev** [comment]
Depends on https://github.com/it-projects-llc/pos-addons/pull/795

**Comment by yelizariev** [comment]
Please read meaning of :shield: and :rainbow: tags

**Review by yelizariev — APPROVED** [review]
Code changes look good

**Review by Ramil-Mukhametzyanov — APPROVED** [review]
Module passed the test on the runbot

**Comment by yelizariev** [comment]
2018-11-12 10:43:09,068 2918 ERROR 23715-797-1c4683-base odoo.modules.graph: module pos_print_method: Unmet dependencies: pos_restaurant_base

**Comment by yelizariev** [comment]
2018-11-13 09:38:35,694 3863 WARNING 23780-797-fc78c0-base odoo.models: The model pos.category_discount has no _description

**Comment by yelizariev** [comment]
Green :green_heart: :green_heart: !

**Pull request merged**
