### PR TITLE
11.0 pos debt notebook error on pay discount credits

### PR DESCRIPTION
**Pull request by KolushovAlexandr**

### CODE REVIEW

**Review by Ramil-Mukhametzyanov — APPROVED** [review]
Full payment is accepted by the credit (via discount) for the products with customer taxes.

**Review by Ramil-Mukhametzyanov — CHANGES_REQUESTED** [review]
The selected zero price payment should be ignored.
The method credit (via discount) is not accepted if any other type of payment is also chosen, even if its value is zero.

**Comment by ilmir-k** [comment]
I need the status of this.
@Ramil-Mukhametzyanov please leave your review

**Review by Ramil-Mukhametzyanov — APPROVED** [review]
Changes are approved

**Comment by ilmir-k** [comment]
@KolushovAlexandr update the versions too

**Pull request merged**
