### PR TITLE
[FIX] sync error during fast change the order

### PR DESCRIPTION
**Pull request by GabbasovDinar**

### CODE REVIEW

**Review by yelizariev — APPROVED** [review]

**Comment by yelizariev** [comment]
@ilmir-k use this commit message on merging

```
[FIX] error on removing right after updating an order

request for order removing must be done after or instead of the request for updating.

Without this update, the script could send a request for an update after sending a request for removing the order. The scenario: 

* update order -- timer start
* remove order -- the request is sent immediately
* timer ends -- request for updating is sent
```

**Review by ilmir-k — APPROVED** [review]

**Comment by ilmir-k** [comment]
@GabbasovDinar fix the remaining lints

**Comment by GabbasovDinar** [comment]
@ilmir-k DONE

**Comment by ilmir-k** [comment]
@yelizariev I can't merge it due to travis warnings

**Comment by yelizariev** [comment]
Those errors have to be fixed

**Comment by yelizariev** [comment]
While the error may be simple and could be ignored, it actually blocks all other checks which might find essential errors

**Comment by GabbasovDinar** [comment]
@yelizariev @ilmir-k DONE

**Pull request merged**
