### PR TITLE
:book: description and screens are updated

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by Ramil-Mukhametzyanov — CHANGES_REQUESTED** [review]
This image does not represent an Odoo 12.0 interface
all_discount_programs
It is also not an Odoo 12.0 interface
create_discount_program
And this is not.
discount_allowed

**Comment by ghost** [comment]
https://github.com/Mirgalimova/pos-addons/blob/12.0_pos_product_category_discount-docs-updated/pos_product_category_discount/static/description/

должны быть новые картинки

**Review by Ramil-Mukhametzyanov — APPROVED** [review]

**Comment by yelizariev** [comment]
check green notes

screenshot-32847-1002-9a4781-base runbot it-projects info-2019 05 30-12-30-32

**Comment by ghost** [comment]
Fails вроде не по моей части
- длинные имена модулей остались
- и вот этот pos_product_category_discount/__init__.py:1: [E7989(readme-versions), ] Wrong version in module's README.rst

**Comment by yelizariev** [comment]
dummy message

**Pull request merged**
