### PR TITLE
[IMP] refactoring and fixing pos_order_cancel, pos_disable_payment

### PR DESCRIPTION
**Pull request by GabbasovDinar**

### CODE REVIEW

**Comment by ilmir-k** [comment]
@GabbasovDinar fix lint errors

**Comment by ilmir-k** [comment]
@GabbasovDinar one more lint to be fixed

**Review by ilmir-k — APPROVED** [review]
:+1:

**Comment by yelizariev** [comment]
Last commit for now: a215d93ac5f4b3183cfda22e76d29c611cc490ec

**Comment by yelizariev** [comment]
@GabbasovDinar clean up commit and make separate commits for  each modules

**Pull request merged**
