### PR TITLE
[FIX] repeats access error message fix

### PR DESCRIPTION
**Pull request by GabbasovDinar**

### CODE REVIEW

**Comment by yelizariev** [comment]
Are you sure, that we don't need to send request_sync_call in case of access_error?

**Comment by yelizariev** [comment]
What access_error actually is?

**Comment by GabbasovDinar** [comment]
@yelizariev, I think yes. When I run the synchronization if access_error then he causes sync is infinitely

**Comment by yelizariev** [comment]
What access_error  is?

**Comment by GabbasovDinar** [comment]
@yelizariev exception type

**Comment by yelizariev** [comment]
You can check whether it was sync_all request and don't send new one and show another wanrning ("Cannot sync") instead

**Comment by yelizariev** [comment]
I mean when access_error happens?

**Comment by yelizariev** [comment]
what is the reason of the error?

**Pull request closed without merging**
