### PR TITLE
:ambulance: pos_reference errors for some localizations

### PR DESCRIPTION
**Pull request by KolushovAlexandr**

### CODE REVIEW

**Review by Ramil-Mukhametzyanov — APPROVED** [review]
:+1:  error 'amount_via_discount' is fixed 
:+1:  error related to the order selection in non-english interface is fixed.

**Comment by yelizariev** [comment]
Consider to fix lints
```


Using config file /home/travis/maintainer-quality-tools/travis/cfg/travis_run_pylint.cfg
************* Module pos_mobile_restaurant.__manifest__
pos_mobile_restaurant/__manifest__.py:1: [C8202(unnecessary-utf8-coding-comment), ] UTF-8 coding is not necessary
************* Module pos_mobile_restaurant.models.__init__
pos_mobile_restaurant/models/__init__.py:1: [C8202(unnecessary-utf8-coding-comment), ] UTF-8 coding is not necessary
************* Module pos_mobile_restaurant.models.pos_config_model
pos_mobile_restaurant/models/pos_config_model.py:1: [C8202(unnecessary-utf8-coding-comment), ] UTF-8 coding is not necessary
************* Module pos_mobile_restaurant.tests.test_default
pos_mobile_restaurant/tests/test_default.py:1: [C8202(unnecessary-utf8-coding-comment), ] UTF-8 coding is not necessary
************* Module pos_orders_history_reprint
pos_orders_history_reprint/__init__.py:1: [C8202(unnecessary-utf8-coding-comment), ] UTF-8 coding is not necessary
************* Module pos_orders_history_reprint.models.model
pos_orders_history_reprint/models/model.py:12: [R7980(consider-merging-classes-inherited), PosConfig] Consider merging classes inherited to "pos.config" from models/model.py:57.

```

**Comment by yelizariev** [comment]
Is it for 10 or 11?
it-projects-llc:10.0 from KolushovAlexandr:11.0-pos-pos_reference-localization_issue

**Comment by KolushovAlexandr** [comment]
@yelizariev it's for 10th, mistakenly called 11

**Review by yelizariev — APPROVED** [review]

**Pull request merged**
