### PR TITLE
:arrow_up::one::two: pos_invoice_pay

### PR DESCRIPTION
**Pull request by GabbasovDinar**

### CODE REVIEW

**Comment by GabbasovDinar** [comment]
I ported the pos_invoice_pay module, you can check @janbec

**Review by ilmir-k — CHANGES_REQUESTED** [review]
Travis is red

**Review by Ramil-Mukhametzyanov — CHANGES_REQUESTED** [review]
Clicking 'Create Invoice' on invoiced order causes the 'event is not defined' error.

**Comment by GabbasovDinar** [comment]
> Clicking 'Create Invoice' on invoiced order causes the 'event is not defined' error.

I cannot reproduce this error

**Comment by ilmir-k** [comment]
What's the next step for this PR?

**Comment by janbec** [comment]
I will try to take a look at it tomorrow :)

Am Do., 27. Dez. 2018, 14:10 hat ILMIR <notifications@github.com>
geschrieben:

**Comment by janbec** [comment]
@GabbasovDinar 
I finally managed to take a look at it. Saw that there are some additional improvements as well, nice!
I noticed the following `singleton `errors occuring:

1. If you have two taxes in one invoice line, singleton error is caused on loading touch interface
2. If you create a credit note from an invoice and choose option `create refund, reconcile, and create new invoice` causes singleton error when opening refund/invoice. To solve this in v11, I decorated `_get_payment_info_JSON` with `@api.one` because it had to be fast. but worked. 

Everything else looks good!

**Comment by janbec** [comment]
@GabbasovDinar 
Here is a screen showing the line causing the first error:
image

hope it helps

**Comment by GabbasovDinar** [comment]
I will update soon

**Comment by GabbasovDinar** [comment]
@janbec I fixed the indicated errors, you can check again

**Comment by janbec** [comment]
@GabbasovDinar My tests passed succesfully, thank you for taking care of this! :)

**Review by Ramil-Mukhametzyanov — CHANGES_REQUESTED** [review]
The POS invoice payment generates a web request with same parameters and gets the same response more 10 or more times after clicking "Create Invoice" button.
In my case, it took 10 second passed before the payment screen is displayed.

**Review by Ramil-Mukhametzyanov — COMMENTED** [review]
Slow Invoice generation speed is independent of migration

**Review by Ramil-Mukhametzyanov — APPROVED** [review]
@ilmir-k Please check the PR

**Comment by janbec** [comment]
@GabbasovDinar 
Hi Dinar,
I just noticed that invoices are not printed anymore when created from sale order. Currently, as soon as we create an invoice, the option Invoice on the payment screen is pre-selected and the user can then easily print the invoice. Do you know if you removed that feature at some point of time?

image

**Review by ilmir-k — CHANGES_REQUESTED** [review]
It seems there is rounding issue. When ``Difference account`` is empty, in some cases we have the warning about a change even if ``amount due = amount tendered``

**Comment by GabbasovDinar** [comment]
@janbec Hi Jan, yes, you're right. I fixed the error :+1:

**Review by yelizariev — APPROVED** [review]
Code LGTM

**Review by ilmir-k — APPROVED** [review]

**Pull request merged**
