### PR TITLE
[DEV] try to get logs about new error on travis

### PR DESCRIPTION
**Pull request by yelizariev**

### CODE REVIEW

**Comment by yelizariev** [comment]
The logs
```

2018-04-30 16:34:58,345 5292 ERROR openerp_test odoo.tests.common: 
phantomjs: u"null is not an object (evaluating 'order.get_paymentlines')
 render_paymentlines@http://127.0.0.1:8069/pos_invoice_pay/static/src/js/main.js:878:26
renderElement@http://127.0.0.1:8069/point_of_sale/static/src/js/screens.js:1839:33
http://127.0.0.1:8069/web/static/src/js/framework/class.js:89:43
renderElement@http://127.0.0.1:8069/pos_disable_payment/static/src/js/pos_disable_payment.js:261:24
http://127.0.0.1:8069/web/static/src/js/framework/class.js:122:43
renderElement@http://127.0.0.1:8069/pos_mobile/static/src/js/screens.js:249:24
http://127.0.0.1:8069/web/static/src/js/framework/class.js:122:43
http://127.0.0.1:8069/web/static/src/js/framework/widget.js:191:31
http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3276:94
fire@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3119:63
add@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3165:53
http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3275:77
each@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:383:62
http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3272:60
Deferred@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3332:34
then@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3271:63
__widgetRenderAndInsert@http://127.0.0.1:8069/web/static/src/js/framework/widget.js:190:37
appendTo@http://127.0.0.1:8069/web/static/src/js/framework/widget.js:129:44
build_widgets@http://127.0.0.1:8069/point_of_sale/static/src/js/chrome.js:767:36
build_widgets@http://127.0.0.1:8069/pos_restaurant/static/src/js/floors.js:705:20
http://127.0.0.1:8069/web/static/src/js/framework/class.js:122:43
build_widgets@http://127.0.0.1:8069/pos_longpolling/static/src/js/pos_longpolling.js:309:24
http://127.0.0.1:8069/web/static/src/js/framework/class.js:122:43
build_widgets@http://127.0.0.1:8069/pos_mobile/static/src/js/chrome.js:13:24
http://127.0.0.1:8069/web/static/src/js/framework/class.js:122:43
build_widgets@http://127.0.0.1:8069/pos_mobile_restaurant/static/src/js/chrome.js:25:24
http://127.0.0.1:8069/web/static/src/js/framework/class.js:122:43
http://127.0.0.1:8069/point_of_sale/static/src/js/chrome.js:479:31
fire@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3119:63
fireWith@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3231:53
http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3283:104
fire@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3119:63
fireWith@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3231:53
http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3321:62
load_model@http://127.0.0.1:8069/point_of_sale/static/src/js/models.js:475:31
http://127.0.0.1:8069/point_of_sale/static/src/js/models.js:508:65
http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3276:94
fire@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3119:63
add@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3165:53
http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3275:77
each@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:383:62
http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3272:60
Deferred@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3332:34
then@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3271:63
http://127.0.0.1:8069/point_of_sale/static/src/js/models.js:508:42
http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3276:94
fire@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3119:63
fireWith@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3231:53
http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3283:104
fire@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3119:63
fireWith@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3231:53
http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3321:62
fire@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3119:63
fireWith@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3231:53
http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3283:104
fire@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3119:63
fireWith@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3231:53
http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3283:104
fire@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3119:63
fireWith@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:3231:53
done@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:9275:53
callback@http://127.0.0.1:8069/web/static/lib/jquery/jquery.js:9685:65
 at http://127.0.0.1:8069/point_of_sale/static/src/js/models.js:511
(leaf frame on top)"
```

**Comment by yelizariev** [comment]
There is a code which lead to error
```
    render_paymentlines: function () {
        var self = this;
        var order = this.pos.get_order();
        if (typeof order !== 'object') {
            return;
        }
```
the problem is that ``typeof null`` is `'object'`

**Comment by GabbasovDinar** [comment]
@yelizariev We need to use
```
if (!order) {
    return;
}
```
without checking the type of variable

**Comment by yelizariev** [comment]
@GabbasovDinar it was like this before, but Artyom fixes some lints

**Pull request closed without merging**
