### PR TITLE
10.0 ms sync conflicts imp fix 4

### PR DESCRIPTION
**Pull request by KolushovAlexandr**

### CODE REVIEW

**Review by yelizariev — COMMENTED** [review]
I don’t understand how poll_response  works

**Comment by yelizariev** [comment]
network_is_on calling in on_notification_do seems to be excessive:

https://github.com/KolushovAlexandr/pos-addons/blob/75cea6b30dd0e13458c7a9923d840ec129c3250d/pos_longpolling/static/src/js/pos_longpolling.js#L146-L153

**Comment by yelizariev** [comment]
Possible renamings:

```
set_poll_status -> rerender_poll_status

status -> is_online

poll_response_status -> waiting_poll_response

set_connecting_status -> icon_rotating(active) (if function is still needed)


```

**Review by yelizariev — APPROVED** [review]
ок

**Comment by yelizariev** [comment]
Update changelog please

**Comment by KolushovAlexandr** [comment]
@yelizariev this PR into 10.0-ms-sync-conflicts, so I updated the last version changes

**Pull request merged**
