### PR TITLE
:ambulance: inproper rights for product configuration

### PR DESCRIPTION
**Pull request by KolushovAlexandr**

### CODE REVIEW

**Review by ilmir-k — APPROVED** [review]

**Comment by KolushovAlexandr** [comment]
I approve to merge it now

**Comment by em230418** [comment]
```
************* Module pos_debt_notebook
pos_debt_notebook/__init__.py:1: [E7988(manifest-name), ] Empty or too long module name. The name must be no more than 25 characters
Odoo version in link http://runbot.it-projects.info/demo/pos-addons/9.0 is not valid
pos_debt_notebook/__init__.py:1: [E7989(readme-versions), ] Wrong version in module's README.rst
```

**Comment by ilmir-k** [comment]
@em230418 travis is ok now

**Review by em230418 — CHANGES_REQUESTED** [review]
Cannot pass tests using odooup.
```
odooup init test  # Odoo 12, no additional repo
cd test
bash
cd vendor
mkdir KolushovAlexandr && cd KolushovAlexandr
git clone git@github.com:KolushovAlexandr/pos-addons.git -b 12.0-pos_debt_notebook-hidden_field
exit
make create && make build
docker-compose run dodoo -- init --new-database db --demo -m point_of_sale,uom,analytic,bus,web_tour,mail,decimal_precision,barcodes,portal,account,base,web_editor,http_routing,stock,base_setup,digest,product,stock_account,web,pos_debt_notebook
docker-compose run odoo -d db --test-enable --stop-after-init -i pos_debt_notebook
```

[tests.log](https://github.com/it-projects-llc/pos-addons/files/3405353/tests.log)

**Comment by yelizariev** [comment]
Consider paste some parts of logs as a comment:


```
2019-07-18 07:47:05,134 1 ESC[1;32mESC[1;49mINFOESC[0m db odoo.addons.pos_debt_notebook.tests.test_pos_debt.TestUi: console log: Tour tour_pos_debt_no
tebook: step .button.paymentmethod:contains("Credits") succeeded 
2019-07-18 07:47:16,146 1 ESC[1;32mESC[1;49mINFOESC[0m db odoo.addons.pos_debt_notebook.tests.test_pos_debt.TestUi: console log: _check_for_tooltip 
2019-07-18 07:47:16,148 1 ESC[1;32mESC[1;49mINFOESC[0m db odoo.addons.pos_debt_notebook.tests.test_pos_debt.TestUi: console log: - modal_displayed: 0 
2019-07-18 07:47:16,149 1 ESC[1;32mESC[1;49mINFOESC[0m db odoo.addons.pos_debt_notebook.tests.test_pos_debt.TestUi: console log: - trigger '.button.ne
xt.highlight:contains("Validate")': 0 
2019-07-18 07:47:16,150 1 ESC[1;32mESC[1;49mINFOESC[0m db odoo.addons.pos_debt_notebook.tests.test_pos_debt.TestUi: console log: - visible trigger '.b
utton.next.highlight:contains("Validate")': 0 
2019-07-18 07:47:16,151 1 ESC[1;32mESC[1;49mINFOESC[0m db odoo.addons.pos_debt_notebook.tests.test_pos_debt.TestUi: console log: - extra_trigger '.but
ton.next.highlight:contains("Validate")': 0 
2019-07-18 07:47:16,152 1 ESC[1;32mESC[1;49mINFOESC[0m db odoo.addons.pos_debt_notebook.tests.test_pos_debt.TestUi: console log: - visible extra_trigger '.button.next.highlight:contains("Validate")': 0 
2019-07-18 07:47:16,209 1 ESC[1;32mESC[1;49mINFOESC[0m db odoo.addons.pos_debt_notebook.tests.test_pos_debt.TestUi: console log: <body class="">
        <div class="o_main_content"><div class="o_control_panel o_hidden"></div><div class="o_content"><div class="pos">
            <div class="pos-topheader">
                <div class="pos-branding">

```

**Comment by yelizariev** [comment]
The error is not related to the updates for sure

**Comment by yelizariev** [comment]
I approve to merge it now

**Pull request merged**
