### PR TITLE
[IMP] single sync_all on a session inition

### PR DESCRIPTION
**Pull request by KolushovAlexandr**

### CODE REVIEW

**Comment by yelizariev** [comment]
Error on travis
```

<pre>TypeError: undefined is not a function (evaluating 'line_ids.includes(lines[i].id)')</pre>
<pre>http://127.0.0.1:8069/web/content/584-1a1f16c/point_of_sale.assets.js:732
```

**Comment by yelizariev** [comment]
```
</div>
<div class="o_error_detail modal-body">
<pre>TypeError: null is not an object (evaluating 'order.get_paymentlines')</pre>
<pre>http://127.0.0.1:8069/web/content/584-64be75b/point_of_sale.assets.js:771
Traceback:
```

**Comment by yelizariev** [comment]
step ``js_connecting:visible `` doesn't work at pos_orderline_absolute_discount_tour

**Comment by yelizariev** [comment]
Lint warnings
```

************* Module pos_longpolling
pos_longpolling/views/pos_longpolling_template.xml:2: [W7939(deprecated-data-xml-node), ]  Use <odoo> instead of <odoo><data> or use <odoo noupdate="1">instead of <odoo><data noupdate="1">
pos_longpolling/views/pos_longpolling_view.xml:2: [W7939(deprecated-data-xml-node), ]  Use <odoo> instead of <odoo><data> or use <odoo noupdate="1">instead of <odoo><data noupdate="1">
Found 2 errors in modules changed.

```

**Review by GabbasovDinar — APPROVED** [review]

**Comment by yelizariev** [comment]
Merged in #709

**Comment by yelizariev** [comment]
https://github.com/it-projects-llc/pos-addons/pull/709/commits/bcf876c5378cc294870a4f026193e8a92e4db361

**Pull request closed without merging**
