### PR TITLE
11.0 f6b8c01066eeb6ff586145ca504639540edd4f6e

### PR DESCRIPTION
**Pull request by KolushovAlexandr**

### CODE REVIEW

**Review by Ramil-Mukhametzyanov — CHANGES_REQUESTED** [review]
The "Sync restaurant orders" module doesn't work after changing longpolling

**Review by Ramil-Mukhametzyanov — COMMENTED** [review]
I checked it again. Multisession works. But longpolling icon is permanently orange. What does it mean?

**Comment by GabbasovDinar** [comment]
@Ramil-Mukhametzyanov see index.rst of the pos_longpolling module

**Review by Ramil-Mukhametzyanov — APPROVED** [review]
The longpolling module has the same behavior on odoo 10.0 now

**Review by yelizariev — APPROVED** [review]

**Pull request merged**
