### PR TITLE
[PORT] porting from 10.0 to 11.0

### PR DESCRIPTION
**Pull request by GabbasovDinar**

### CODE REVIEW

**Review by yelizariev — APPROVED** [review]
code is reviewed

**Comment by ilmir-k** [comment]
@GabbasovDinar add `test: true` into https://github.com/it-projects-llc/pos-addons/blob/11.0/pos_order_cancel/static/src/js/tour.js

see for example https://github.com/it-projects-llc/pos-addons/blob/11.0/pos_disable_payment/static/src/js/tour.js

**Comment by yelizariev** [comment]
- [x] don't use ``_t`` for tests only tour 

                     content: _t("<p>Click <b>table</b></p>"),

**Review by yelizariev — CHANGES_REQUESTED** [review]
don't use _t for tests only tour

**Review by yelizariev — APPROVED** [review]

**Review by ilmir-k — APPROVED** [review]
It can be merged

**Pull request merged**
