### PR TITLE
[FIX] Check for correct response type to prevent undefined sequence_n…

### PR DESCRIPTION
**Pull request by pedroslopez**
…umber

### CODE REVIEW

**Comment by yelizariev** [comment]
@pedroslopez I think, that we already fixed the problem #330 with this commit: https://github.com/it-projects-llc/pos-addons/commit/a3a8685143a0e0cdc107a2a57aeedf5899460053 which makes similar thing: prevents to set empty sequence_number value

@GabbasovDinar Am I right? Shall we merge this PR?

**Comment by pedroslopez** [comment]
@yelizariev I commented on the original issue (#330), but I'll quote it here just because it's related

>  This does fix the issue when it occurs when removing an order, but not when a revision_error is thrown on set_order

**Comment by yelizariev** [comment]
@GabbasovDinar can you confirm [that](https://github.com/it-projects-llc/pos-addons/pull/355#issuecomment-323247494)? Can there be other responses that need to be handled same way as update_revision_ID?

**Comment by GabbasovDinar** [comment]
@yelizariev , @pedroslopez Yes, I confirm this. The do_ms_update function did not take check when the server function returned a "revision error" and this fixes it.

Thanks, good work!

**Comment by pedroslopez** [comment]
Great to hear!

Can this be back ported to the 9.0 branch? The same issue is present.

**Pull request merged**
