### PR TITLE
Add devices Galaxy Tab/Alcatel

### PR DESCRIPTION
**Pull request by Ark74**
Galaxy Tab/Alcatel

- galaxy tab
Mozilla/5.0 (Linux; Android 6.0.1; Galaxy Tab 2)...

- 900[0-9][A-Z]
Mozilla/5.0 (Linux; Android 8.1.0; 9009G)...

### CODE REVIEW

**Comment by em230418** [comment]
Does not seem to work
https://jsfiddle.net/gzj29b3v/8/

**Comment by Ark74** [comment]
Weird both have been tested with the actual device and they did work. :confused:

**Comment by yelizariev** [comment]
@Ark74 could you provide complete User-Agent values?

**Comment by Ark74** [comment]
Here:

```
Mozilla/5.0 (Linux; Android 6.0.1; Galaxy Tab 2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.101 Safari/537.36

Mozilla/5.0 (Linux; Android 8.1.0; 9009G) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.101 Safari/537.36
```

**Comment by Ark74** [comment]
Ohh! I see my error. I moved them on the PR to fit incremental order. Later on I guess I was having a cached browser response.
Let me correct.

**Review by em230418 — CHANGES_REQUESTED** [review]
https://jsfiddle.net/nq6orybs/1/ - original regex
https://jsfiddle.net/q8h2wsc9/5/ - modified regex.
Desktop browsers are detected as mobile.

**Comment by Ark74** [comment]
@em230418  Removed leading pipe causing that issue.

**Comment by Ark74** [comment]
Anything else missing?

**Comment by em230418** [comment]
> Anything else missing?

No, just dealing with other todos. Sorry for the delay and thanks!

**Comment by em230418** [comment]
I approve to merge it now

**Pull request merged**
