### PR TITLE
8.0 tg_pos_debt_notebook: Add button "pay full debt" 

### PR DESCRIPTION
**Pull request by alexis-via**
Add button "pay full debt" to make it easier for the user to manage the scenario where a customer comes to pay his debt

Enhance/cleanup JS code
Declare CSS file in XML, as done in other modules
Update POT file and FR translation

### CODE REVIEW

**Comment by yelizariev** [comment]
There is small issue.
Debt is not updated after clicking "Full debt Button"

selection_001
It is updated only after adding new line
selection_002

**Comment by yelizariev** [comment]
I suggest to show current Debt inside Button:

```
Pay Full Debt
(4813.00)
```

Or maybe change title to:

```
Current debt: 4813.00
```

**Comment by yelizariev** [comment]
I am sorry, I didn't notice Debt value at Tab. So, we don't need debt value at button

**Comment by alexis-via** [comment]
@yelizariev Thanks for your review. I also noticied that the debt amount is only updated when a new payment line is added... I'll try to find the technique to do that. If someone has an idea on the proper technique to do that, it would be very much appreciated.

**Comment by yelizariev** [comment]
Alexis,
thank you for your work.

Could you fix css issue
odoo - google chrome_001

**Comment by yelizariev** [comment]
I think button "Select Customer and pay full debt" can be located near Debt field.

Also, I suggest to hide Pay debt buttons when customer don't have debts

**Comment by yelizariev** [comment]
Alexis,
thank you for new commits.

Could you please update version and add changlelog to modules.

**Comment by yelizariev** [comment]
@alexis-via I'd like to merge your update. Do you want to add something else and need some time? If not, could you please set version to '1.0.2' in __openerp__.py file and add short notes in doc/changelog.rst
Also, if you like, feel free to add your name at author list or at module description.

**Pull request merged**
