### PR TITLE
Change server date time to user timezone

### PR DESCRIPTION
**Pull request by iceship**
Change server date time to user timezone

### CODE REVIEW

**Comment by yelizariev** [comment]
I am not sure shall we make this update on server or on client side.
Have you checked how point_of_sale module handles timezones?

**Comment by ufaks** [comment]
I got the error when I clicked on the "Show debt history" button

Odoo Server Error
Traceback (most recent call last):
  File "/mnt/odoo-extra/runbot/static/build/05332-296-a5e549/odoo/http.py", line 638, in _handle_exception
    return super(JsonRequest, self)._handle_exception(exception)
  File "/mnt/odoo-extra/runbot/static/build/05332-296-a5e549/odoo/http.py", line 675, in dispatch
    result = self._call_function(**self.params)
  File "/mnt/odoo-extra/runbot/static/build/05332-296-a5e549/odoo/http.py", line 331, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/mnt/odoo-extra/runbot/static/build/05332-296-a5e549/odoo/service/model.py", line 119, in wrapper
    return f(dbname, *args, **kwargs)
  File "/mnt/odoo-extra/runbot/static/build/05332-296-a5e549/odoo/http.py", line 324, in checked_call
    result = self.endpoint(*a, **kw)
  File "/mnt/odoo-extra/runbot/static/build/05332-296-a5e549/odoo/http.py", line 933, in __call__
    return self.method(*args, **kw)
  File "/mnt/odoo-extra/runbot/static/build/05332-296-a5e549/odoo/http.py", line 504, in response_wrap
    response = f(*args, **kw)
  File "/mnt/odoo-extra/runbot/static/build/05332-296-a5e549/odoo/addons/web/controllers/main.py", line 885, in call_kw
    return self._call_kw(model, method, args, kwargs)
  File "/mnt/odoo-extra/runbot/static/build/05332-296-a5e549/odoo/addons/web/controllers/main.py", line 877, in _call_kw
    return call_kw(request.env[model], method, args, kwargs)
  File "/mnt/odoo-extra/runbot/static/build/05332-296-a5e549/odoo/api.py", line 681, in call_kw
    return call_kw_multi(method, model, args, kwargs)
  File "/mnt/odoo-extra/runbot/static/build/05332-296-a5e549/odoo/api.py", line 672, in call_kw_multi
    result = method(recs, *args, **kwargs)
  File "/mnt/odoo-extra/runbot/static/build/05332-296-a5e549/odoo/addons/pos_debt_notebook/models.py", line 69, in debt_history
    r2['date'] = self._get_date_formats(r2['date'])
  File "/mnt/odoo-extra/runbot/static/build/05332-296-a5e549/odoo/addons/pos_debt_notebook/models.py", line 96, in _get_date_formats
    date_format = lang.browse(lang_id).date_format
  File "/mnt/odoo-extra/runbot/static/build/05332-296-a5e549/odoo/fields.py", line 870, in __get__
    self.determine_value(record)
  File "/mnt/odoo-extra/runbot/static/build/05332-296-a5e549/odoo/fields.py", line 972, in determine_value
    record._prefetch_field(self)
  File "/mnt/odoo-extra/runbot/static/build/05332-296-a5e549/odoo/models.py", line 3070, in _prefetch_field
    result = records.read([f.name for f in fs], load='_classic_write')
  File "/mnt/odoo-extra/runbot/static/build/05332-296-a5e549/odoo/models.py", line 3010, in read
    self._read_from_database(stored, inherited)
  File "/mnt/odoo-extra/runbot/static/build/05332-296-a5e549/odoo/models.py", line 3138, in _read_from_database
    cr.execute(query_str, params)
  File "/mnt/odoo-extra/runbot/static/build/05332-296-a5e549/odoo/sql_db.py", line 141, in wrapper
    return f(self, *args, **kwargs)
  File "/mnt/odoo-extra/runbot/static/build/05332-296-a5e549/odoo/sql_db.py", line 218, in execute
    res = self._obj.execute(query, params)
  File "/usr/lib/python2.7/dist-packages/psycopg2/extensions.py", line 129, in getquoted
    pobjs = [adapt(o) for o in self._seq]
ProgrammingError: can't adapt type 'res.lang'

**Comment by yelizariev** [comment]
@iceship in Receipt odoo use js converting:

    date.toLocaleString(),

it should be more easy to implement. What do you think?

**Comment by yelizariev** [comment]
@ufaks I've fixed the issue you found

**Comment by yelizariev** [comment]
It works. Thank you @iceship for sharing

**Pull request merged**
