### PR TITLE
:heart_eyes: show the autostart_longpolling setting after install Multi Session module

### PR DESCRIPTION
**Pull request by GabbasovDinar**

### CODE REVIEW

**Review by yelizariev — CHANGES_REQUESTED** [review]
What if we have two modules that use pos_longpolling as dependency? They both add the field? What you can do is keep field in pos_longpolling, but hide it there. Then you disable hiding in pos_multi_session

**Comment by GabbasovDinar** [comment]
@yelizariev I don't understand what do you mean. Only pos_multi_session module add the new field

**Comment by KolushovAlexandr** [comment]
@GabbasovDinar He means to put `invisible="1"` attribute to the `autostart_longpolling` field in pos_longpolling and then make it visible again in pos_multi_session module

**Comment by KolushovAlexandr** [comment]
superseded by https://github.com/it-projects-llc/pos-addons/pull/1044

**Pull request closed without merging**
