### PR TITLE
[ADD] add many2many 

### LINKED ISSUE #404: [pos_order_cancel] save pos.cancelled_reason.id in pos.order.line.canceled
hello,

it should be a great idea to save pos.cancelled_reason.id in pos.order.line.canceled

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/49627196-pos_order_cancel-save-pos-cancelled_reason-id-in-pos-order-line-canceled?utm_campaign=plugin&utm_content=tracker%2F2289114&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F2289114&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by GabbasovDinar**
add many2many relation between pos.cancelled_reason and pos.order.line.canceled
fix #404

### CODE REVIEW

**Comment by flotho** [comment]
Hi @yelizariev , @GabbasovDinar 

Any news for this one?

regards

**Comment by ilmir-k** [comment]
Hi @flotho 

We should add tests to this one to increase coverage and then we will merge it. We are working on it.

**Comment by flotho** [comment]
@ilmir-k thanks for your feedback

**Review by ilmir-k — APPROVED** [review]
approved

**Pull request merged**
