### PR TITLE
[FIX] Duplicated event listener

### PR DESCRIPTION
**Pull request by ssaid**

### CODE REVIEW

**Comment by ssaid** [comment]
This issue can be seen with the module pos_invoice_pay installed: the event handler for keyboard is called twice.

**Review by Ramil-Mukhametzyanov — COMMENTED** [review]
@ssaid Hello. Thanks for your pull request. We will check it out.

**Review by Ramil-Mukhametzyanov — COMMENTED** [review]
The issue is reproduced.

**Review by Ramil-Mukhametzyanov — APPROVED** [review]

**Review by KolushovAlexandr — APPROVED** [review]
Thank you for contributing! I found the same problem in 10v so updated your commit according to our company rules and made a request to 10v. Later it will be merged into 11v too. You can see it here https://github.com/it-projects-llc/pos-addons/pull/1024

**Comment by ssaid** [comment]
@KolushovAlexandr I have done a new PR because it is still not merged against v11: #1070 
Thanks!

**Pull request closed without merging**
