### PR TITLE
9.0 get client

### LINKED ISSUE #70: get the client's name with the pos_multi_session
hello, 

I want to get the client's name on other session, so I modified : 

```
`ms_my_info: function(){
            var user = this.cashier || this.user;
            return {
                'user': {
                    'id': user.id,
                    'name': user.name,
                },
                'pos': {
                    'id': this.config.id,
                    'name': this.config.name,
                },
                'client':this.get_client(),
            }
        }

 ms_do_update: function(order, data){
            var pos = this;
            var sequence_number = data.sequence_number;
            if (!order){
                var create_new_order = pos.config.multi_session_accept_incoming_orders || !(data.ms_info && data.ms_info.created.user.id != pos.ms_my_info().user.id)
                if (sequence_number == this.pos_session.sequence_number){
                    //ok
                } else if (sequence_number > this.pos_session.sequence_number){
                    // this pos has obsolete sequence_number
                    this.pos_session.sequence_number = sequence_number;
                } else if (sequence_number < this.pos_session.sequence_number){
                    // another pos has obsolete sequence_number
                    pos.multi_session.sync_sequence_number();
                    if (create_new_order)
                        this.pos_session.sequence_number--; // decrease temporarily, because it is increased right after creating new order
                }
                if (!create_new_order){
                    return;
                }
                order = this.ms_create_order({ms_info:data.ms_info,data:data})
                order.uid = data.uid;
                order.sequence_number = data.sequence_number
                var current_order = this.get_order();
                this.get('orders').add(order);
                this.ms_on_add_order(current_order);
            } else {
                order.ms_info = data.ms_info;
            }

          //-----------------added code----------------------

            var client = order.ms_info.client;
            order.set_client(client);

          //-------------------------------------------------------

            var not_found = order.orderlines.map(function(r){
                                return r.uid;
                            })
            _.each(data.lines, function(dline){
                dline = dline[2];
                var line = order.orderlines.find(function(r){
                    return dline.uid == r.uid
                })
                not_found = _.without(not_found, dline.uid);
                var product = pos.db.get_product_by_id(dline.product_id);
                if (!line){
                    line = new models.Orderline({}, {pos: pos, order: order, product: product});
                    line.uid = dline.uid
                }
                line.ms_info = dline.ms_info || {}
                if(dline.qty !== undefined){
                    line.set_quantity(dline.qty);
                }
                if(dline.price_unit !== undefined){
                    line.set_unit_price(dline.price_unit);
                }
                if(dline.discount !== undefined){
                    line.set_discount(dline.discount);
                }
                order.orderlines.add(line)
            })

            _.each(not_found, function(uid){
                var line = order.orderlines.find(function(r){
                               return uid == r.uid;
                           })
                order.orderlines.remove(line);
            })

        }
`
```

But I get with my debug mode the object order->ms_info->changed->client (the attribute has my new client).

With the above code order.ms_info.client = NULL and if I replace it by order.ms_info.changed.client, I have error :  order.ms_info.changed.client not found

Do you have idea to resolve this problem? or I have error in my added code?

Edit : I see that the partner_id is send, but my client is not changed on others pos, it's a bug?

### PR DESCRIPTION
**Pull request by flotho**
Related to https://github.com/yelizariev/pos-addons/issues/70

closes #70

### CODE REVIEW

**Comment by yelizariev** [comment]
@flotho it's a great work, thank you!
we will upload your updates ourself, because we need to make backport to 8.0, update changelog etc.

cc @ilyasProgrammer

**Comment by flotho** [comment]
Hi @yelizariev ,

Actually this job is a work of @gaelTorrecillas who is a great developper

**Comment by yelizariev** [comment]
@flotho 
I got it. Thank you for sharing his work

**Comment by flotho** [comment]
Hi @yelizariev , does that means that this is now part of the v9?

regards

**Comment by yelizariev** [comment]
Right, it was merged in #77

**Pull request closed without merging**
