### PR TITLE
:rainbow: ms methods renamings

### PR DESCRIPTION
**Pull request by KolushovAlexandr**

### CODE REVIEW

**Comment by KolushovAlexandr** [comment]
external tests passed

**Review by yelizariev — APPROVED** [review]
Looks good

**Comment by yelizariev** [comment]
@ilmir-k @GabbasovDinar I suggest to merge this before any other PR

**Comment by yelizariev** [comment]
Probably ``change:new_updates_to_send`` may be renamed to ``new_updates_to_send``

**Review by GabbasovDinar — APPROVED** [review]
:+1:

**Pull request merged**
